<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link href="style.css" rel="stylesheet">
</head>
<body>

<div class="table-responsive" id="table_patient">

    <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered">
        <!-- le head du tableau-->
        <thead >
        <tr style="margin-left:40px ">
            <th id="id" role="gridcell" style="border-style: solid;  background-color: green"; class="table-bordered">Nombre des Patients:</th>
        </tr>
        </thead>
        <tbody>
                <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try
{
	// On se connecte à MySQL
	$bdd = new PDO('mysql:host=localhost;dbname=consultation_medical;charset=utf8', 'root', '');
	
}
catch(Exception $e)
{
	// En cas d'erreur, on affiche un message et on arrête tout
        die('Erreur : '.$e->getMessage());
}/*

        $select=$bdd->prepare("SELECT count(*) as nb FROM user ");
       $select->execute();
       $s=$select->fetch();
       
       echo $s->nb;
   */    
        ?>

        <tbody>
    </table>


<div >

    <table >
        <!-- le head du tableau-->
        <thead >
        <tr style="margin-right: 400px ">
            <th  style="border-style: solid;  background-color: green"; class="table-bordered">Nombre des RDV:</th>
        </tr>
        </thead>
        <tbody>
                <!--ici on recupere les donnee du tab de la bdd -->
        <?php
        try
{
	// On se connecte à MySQL
	$bdd = new PDO('mysql:host=localhost;dbname=consultation_medical;charset=utf8', 'root', '');
	
}
catch(Exception $e)
{
	// En cas d'erreur, on affiche un message et on arrête tout
        die('Erreur : '.$e->getMessage());
}/*

        $select=$bdd->prepare("SELECT count(*) as nb FROM user ");
       $select->execute();
       $s=$select->fetch();
       
       echo $s->nb;
   */    
        ?>

        <tbody>
    </table>


</body>
</html>