 <table id="autoGeneratedID" role="grid" class="table  table-bordered" style="width: 550px;">
        <!-- le head du tableau-->
        <thead >
        <tr style="background-color:white">
           <!-- <th id="nom"role="gridcell">Nom</th>
            <th id="prenom" role="gridcell">Prénom</th>-->
            <th id="nom_rdv"role="gridcell">Nom rendez-vous</th>
            <th id="date" role="gridcell">Date</th>
            <th id="HD" role="gridcell">Heure debut</th>
            <th id="HF" role="gridcell">Heure fin</th>
        </tr>
        </thead>
     
          <tbody>
    
      <!--ici on recupere les donnee du tab de la bdd -->

    <?php
    
     try
     {
         // On se connecte à MySQL
         $bdd = new PDO('mysql:host=localhost;dbname=db_healthcare;charset=utf8', 'root', '');
     }
     catch(Exception $e)
     {
         // En cas d'erreur, on affiche un message et on arrête tout
             die('Erreur : '.$e->getMessage());
     }
     
     // Si tout va bien, on peut continuer
     
     // On récupère tout le contenu de la table jeux_video
     $reponse = $bdd->query('SELECT * FROM rdv');
     
     // On affiche chaque entrée une à une
     while ($donnees = $reponse->fetch()){
            ?>
            <tr>

               
               <!-- <td id="nom" role="gridcell"><?php// echo $donnees['Nom_patient'];?></td>
                <td id="prenom" role="gridcell"><?php //echo $donnees['Prénom_patient'];?></td>-->
                <td id="nom_rdv" role="gridcell"><?php echo $donnees['Titre'];?></td>
                <td id="date" role="gridcell"><?php echo $donnees['Date_rendez_vous'];?></td>
                <td id="HD" role="gridcell"><?php echo $donnees['Heure_debut'];?></td>
                <td id="HF" role="gridcell"><?php echo $donnees['Heure_fin'];?></td>
                
                
                
               
                
            </tr>
            <?php
            }
            $reponse->closeCursor(); // Termine le traitement de la requête?>

        </tbody>
   
        </table>